bg = "#fbf1c7"
fg = "#504945"
dim = "#bdae93"
error = "#9d0006"
accent = "#076678"
cursor_fg = "#fbf1c7"
cursor_bg = "#b57614"
left_hand = "#79740e"
right_hand = "#8f3f71"
heat_good = "#79740e"
heat_mid = "#b57614"
heat_bad = "#9d0006"
heat_unknown = "#bdae93"
