bg = "#faf4ed"
fg = "#575279"
dim = "#9893a5"
error = "#b4637a"
accent = "#907aa9"
cursor_fg = "#faf4ed"
cursor_bg = "#d7827e"
left_hand = "#286983"
right_hand = "#ea9d34"
heat_good = "#286983"
heat_mid = "#d7827e"
heat_bad = "#b4637a"
heat_unknown = "#9893a5"
